package org.example.api;

public enum ErrorCode {
    BUSINESS_RULE_VIOLATION,
    VALIDATION_FAILED,
    INTERNAL_ERROR,
    RESOURCE_NOT_FOUND,
    INSUFFICIENT_BALANCE,
    KYC_NOT_COMPLETED,
    BANK_ACCOUNT_NOT_FOUND,
    OTP_REQUIRED,
    OTP_INVALID,
    OTP_EXPIRED,
    SESSION_INVALID
}
